/**
 * Created by prasoon on 13/11/16.
 */

export const PLACE_DATA_LOADING = 'PLACE_DATA_LOADING';
export const PLACE_DATA_LOADED = 'PLACE_DATA_LOADED';

export const USER_CURRENT_LOCATION_UPDATE = 'USER_CURRENT_LOCATION_UPDATE';
export const USER_LAST_LOCATION_UPDATE = 'USER_LAST_LOCATION_UPDATE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const PLACE_STATUS_SENDING = 'PLACE_STATUS_SENDING';
export const PLACE_STATUS_SENT = 'PLACE_STATUS_SENT';
